"""Auth repository interfaces (Protocol classes).

The domain layer declares *what* it needs; the infra layer provides
concrete implementations.  Using ``typing.Protocol`` means the
implementations don't need to inherit - structural subtyping is enough.
"""

from typing import Protocol

from app.domain.auth.entity import Permission, Role, User

# ── User ──────────────────────────────────────────────────────────────────


class UserRepository(Protocol):
    """Persistence operations for ``User`` entities."""

    async def find_by_id(self, user_id: int) -> User | None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def find_all(self, offset: int = 0, limit: int = 20) -> list[User]: ...
    async def save(self, user: User) -> User: ...
    async def update(self, user_id: int, **fields: object) -> User | None: ...
    async def delete(self, user_id: int) -> bool: ...
    async def add_role(self, user_id: int, role_id: int) -> None: ...


# ── Role ──────────────────────────────────────────────────────────────────


class RoleRepository(Protocol):
    """Persistence operations for ``Role`` entities."""

    async def find_by_id(self, role_id: int) -> Role | None: ...
    async def find_by_name(self, name: str) -> Role | None: ...
    async def find_all(self, offset: int = 0, limit: int = 20) -> list[Role]: ...
    async def save(self, role: Role) -> Role: ...
    async def update(self, role_id: int, **fields: object) -> Role | None: ...
    async def delete(self, role_id: int) -> bool: ...
    async def add_permission(self, role_id: int, permission_id: int) -> None: ...


# ── Permission ────────────────────────────────────────────────────────────


class PermissionRepository(Protocol):
    """Persistence operations for ``Permission`` entities."""

    async def find_by_id(self, permission_id: int) -> Permission | None: ...
    async def find_by_name(self, name: str) -> Permission | None: ...
    async def find_all(self, offset: int = 0, limit: int = 20) -> list[Permission]: ...
    async def save(self, permission: Permission) -> Permission: ...
    async def update(self, permission_id: int, **fields: object) -> Permission | None: ...
    async def delete(self, permission_id: int) -> bool: ...


# ── Token ─────────────────────────────────────────────────────────────────


class TokenRepository(Protocol):
    """JWT allow-list operations backed by Redis."""

    async def allow(self, jti: str, ttl: int) -> None: ...
    async def is_allowed(self, jti: str) -> bool: ...
    async def revoke(self, jti: str) -> None: ...
    async def revoke_all(self, username: str) -> None: ...

    async def get_cached_scopes(self, username: str) -> list[str] | None: ...
    async def cache_scopes(self, username: str, scopes: list[str], ttl: int) -> None: ...
    async def clear_cached_scopes(self, username: str) -> None: ...
